# Generated by Django 4.1.2 on 2022-11-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monograph',
            name='date_created',
            field=models.DateField(),
        ),
    ]
