# Generated by Django 4.1.2 on 2022-10-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_advirsor_id_advisor_alter_author_id_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monograph',
            name='fk_advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientador', to='records.advirsor'),
        ),
        migrations.AlterField(
            model_name='monograph',
            name='fk_co_advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_orientador', to='records.co_advirsor'),
        ),
        migrations.AlterField(
            model_name='monograph',
            name='fk_id_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='records.author'),
        ),
    ]
