# Generated by Django 4.1.1 on 2022-11-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_monograph_fk_id_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monograph',
            name='fk_advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to='records.advisor'),
        ),
    ]
