# Generated by Django 4.1.1 on 2022-11-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_monograph_fk_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monograph',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
